name: Deploy Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: davidedwards12
          password: Applejack.2021
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./GameMicroServer/Dockerfile
          push: true
          tags: davidedwards12/gamemicro:latest
          
      - name: Run Deploy script on the server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: http://18.233.180.198/
          username: ec2-user
          password: admin
          port: 22
          script: |
            cd scripts
            ./redeployMicro.sh
